# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests/integration_tests",
    "tests/unit_tests",
]
pythonpath = [
    "./",
    "./backend",
    "./content-loading"
]
[pytest]
env_files = [".env"]
